# Generated by Django 3.2 on 2022-11-08 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='trainers',
            options={'verbose_name_plural': 'trainers'},
        ),
    ]
