# Generated by Django 3.2 on 2022-11-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20221108_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='about',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
