# Generated by Django 3.2 on 2022-11-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_memberships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberships',
            options={'verbose_name_plural': 'Memberships'},
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='description',
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='image',
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.memberships'),
        ),
    ]
