# Generated by Django 3.2 on 2022-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberships',
            name='membership_lenght',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
