# Generated by Django 3.2 on 2022-11-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_memberships_membership_lenght'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='membership_lenght',
        ),
        migrations.AddField(
            model_name='product',
            name='membership_lenght',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
