# Generated by Django 3.2 on 2022-11-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221114_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memberships',
            new_name='Category',
        ),
    ]
