# Generated by Django 3.2 on 2022-11-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_membership_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'category'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='membership_lenght',
            new_name='membership_length',
        ),
    ]
